version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    networks:
      - elantar_net
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

networks:
  elantar_net:
    driver: bridge

volumes:
  n8n_data: